apiVersion: v1
kind: Service
metadata:
  name: sample-springboot-app-svc
spec:
    ports:
    - name: "sample-springboot-app"
      targetPort: 8080
      port: 80
      protocol: TCP
    selector:
      app: sample-springboot-app
    type: Loadbalancer

